TwinleafTownHouse1_MapScripts::
	.byte 0


TwinleafTownHouse1_EventScript_Man::
# 5 "data/maps/TwinleafTownHouse1/scripts.pory"
	lock
# 6 "data/maps/TwinleafTownHouse1/scripts.pory"
	faceplayer
# 7 "data/maps/TwinleafTownHouse1/scripts.pory"
	msgbox TwinleafTownHouse1_EventScript_Man_Text_0
# 9 "data/maps/TwinleafTownHouse1/scripts.pory"
	release
	return


TwinleafTownHouse1_EventScript_Man_Text_0:
# 7 "data/maps/TwinleafTownHouse1/scripts.pory"
	.string "You're off to hang with Barry\n"
	.string "again, right? You two sure are tight!$"
